#before_install:
#  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
#  - sudo apt-get update -qq

sudo: required
dist: trusty

env:
  global:
    - ROS_DISTRO=indigo
    - ROS_CI_DESKTOP="`lsb_release -cs`"  # e.g. [precise|trusty|...]
    - CI_SOURCE_PATH=$(pwd)
    - ROSINSTALL_FILE=$CI_SOURCE_PATH/dependencies.rosinstall
    - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
    - ROS_PARALLEL_JOBS='-j8 -l6'

branches:
  only: 
    - master
    - dev

script:
#  - export DEBIAN_FRONTEND=noninteractive
#  - apt-get -o Dpkg::Options::="--force-confnew" install -y 
  - bash -e ./step0.bash
  - bash -e ./step1.bash

